# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

substitutions:
  _TERRAFORM_VERSION: 1.1.6
  _TERRAFORM_VERSION_SHA256SUM: 3e330ce4c8c0434cdd79fe04ed6f6e28e72db44c47ae50d01c342c8a2b05d331
  _TERRAGRUNT_VERSION: 0.36.2
  _TERRAGRUNT_VERSION_SHA256SUM: 0bf8322f73a0ccb1067774ea6b1b7691aeeeea880cffe74111dd5abae7662ac6

steps:
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "TERRAFORM_VERSION=${_TERRAFORM_VERSION}"
      - "TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}"
      - "TERRAGRUNT_VERSION=${_TERRAGRUNT_VERSION}"
      - "TERRAGRUNT_VERSION_SHA256SUM=${_TERRAGRUNT_VERSION_SHA256SUM}"
    args:
      - "build"
      - --build-arg
      - TERRAFORM_VERSION=${_TERRAFORM_VERSION}
      - --build-arg
      - TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}
      - --build-arg
      - TERRAGRUNT_VERSION=${_TERRAGRUNT_VERSION}
      - --build-arg
      - TERRAGRUNT_VERSION_SHA256SUM=${_TERRAGRUNT_VERSION_SHA256SUM}
      - --tag
      - "gcr.io/${PROJECT_ID}/terragrunt:${_TERRAFORM_VERSION}-${_TERRAGRUNT_VERSION}"
      - --tag
      - "gcr.io/${PROJECT_ID}/terragrunt:latest"
      - "."
images:
  - "gcr.io/${PROJECT_ID}/terragrunt:${_TERRAFORM_VERSION}-${_TERRAGRUNT_VERSION}"
  - "gcr.io/${PROJECT_ID}/terragrunt:latest"
tags: ["cloud-builders-community"]
